# Generated by Django 4.2.2 on 2023-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('password', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.TextField()),
                ('phoneNumber', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
