# Generated by Django 4.2.2 on 2023-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='phoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
